const SALEM_LOCATIONS = [
  "Kondalampatti",
  "Seelanaickenpatti",
  "Dadagapatti",
  "Gugai",
  "Ammapet",
  "Hasthampatti",
  "Fairlands",
  "Alagapuram",
  "Suramangalam",
  "Five Roads",
  "Four Roads",
  "Kannankurichi",
  "Pallapatti",
  "Gorimedu",
  "Maravaneri",
  "Shevapet",
  "Johnsonpet",
  "Meyyanur",
  "Narasothipatti",
  "Erumapalayam",
  "Ariyanoor",
  "Jagir Ammapalayam",
  "Asthampatti",
  "Annadanapatti",
  "Kitchipalayam",
  "Karungalpatti",
  "Ponnammapet",
  "Arisipalayam",
  "Swarnapuri",
  "Chinna Thirupathi",
  "Periya Pudur",
  "Alagapuram Pudur",
  "Kandhampatti",
  "Sandaipettai",
  "Thiruvagoundanur",
  "Moolapalayam",
  "Kondappanaickenpatti",
  "Sivathapuram",
  "Kuranguchavadi",
  "Udayapatti",
].map((loc) => loc.toLowerCase());

module.exports = { SALEM_LOCATIONS };
